language: cpp
os:
  - linux
sudo: required
dist: trusty
compiler:
  - gcc
addons:
  apt:
    packages:
    - gcc-4.8
    - g++-4.8
    - libdbus-glib-1-dev
    - libegl1-mesa-dev
    - libgconf2-dev
    - libnss3-dev
    - libpangocairo
    - libxtst-dev
    - python-openssl
before_script:
  - ./travis/setup.sh
script:
  - ./travis/build.sh
