language: cpp
os:
  - linux
  # - osx
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - libdbus-glib-1-dev
    - libegl1-mesa-dev
    - libgconf2-dev
    - libnss3-dev
    - libxtst-dev
    - python-openssl
before_script:
  - ./travis/setup.sh
script:
  - ./travis/build.sh
